<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>vWheelHub</AssemblyName>
    <Product>vWheel Hub</Product>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.1</Version>
    <AssemblyVersion>$(Version).0.0</AssemblyVersion>
    <FileVersion>$(Version).0.0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Company>Barden-dev</Company>
    <Copyright>Copyright (c) 2026 Barden-dev. All Rights Reserved.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
    <Resource Include="Assets\Icons\*.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <Compile Remove="vWheelHub.Tests\**" />
    <Page Remove="tests\**" />
    <Page Remove="vWheelHub.Tests\**" />
    <ApplicationDefinition Remove="tests\**" />
    <ApplicationDefinition Remove="vWheelHub.Tests\**" />
    <None Include="templates\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="vJoyInterface.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\Plugins\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\BeamNG\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Profiles\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

